version: '3.8'

services:
  backend:
    image: harshalargade/gaonwala-backend:latest
    container_name: gaonwala-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads

  frontend:
    image: harshalargade/gaonwala-frontend:latest
    container_name: gaonwala-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  uploads_data: